# Generated by Django 4.2.4 on 2023-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(default='', max_length=12)),
                ('comp_vers', models.CharField(default='', max_length=49)),
                ('comp_summa', models.CharField(default='', max_length=123456)),
                ('date_of_created', models.DateField()),
                ('other_info', models.CharField(default='', max_length=35433983730)),
            ],
        ),
    ]
